run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports

issues:
  exclude-rules:
    - linters:
        - gofmt
      text: "File is not `gofmt`-ed with `-s`"

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/papawattu/cleanlog